feat(new checks): add new asserts
ekino/behat-helpers pull request #6
Opened 2018-11-21 13:16 UTC by bdejacobet

- [x] add some extra assert methods
- [x] add some extra session methods
- [x] add PHP unit tests

2018-12-03 14:30 UTC, mremi commented
@bdejacobet Can you rebase please?

2018-12-10 09:46 UTC, mremi commented on src/ExtraSessionTrait.php
> +    public function iWaitUntilCssElementBeingVisible($element)
Duplicated with `iWaitForCssElementBeingVisible`?

2018-12-10 09:46 UTC, mremi commented on src/ExtraSessionTrait.php
> +    public function iWaitUntilCssElementBeingInvisible($element)
Duplicated with `iWaitForCssElementBeingInvisible`?

2018-12-10 09:46 UTC, mremi commented on src/ExtraSessionTrait.php
> +    public function iClickOnCssElement($selector)
Already exists `clickElement` you remove in this PR, that is a BC break for the projects using this lib

2018-12-14 08:28 UTC, mremi commented on src/ExtraSessionTrait.php
> +        $this->spin(function (MinkContext $context) use ($element) {
`spin` method does the same job as the existing code right? I mean already handled natively by Behat with `wait`

2018-12-18 14:28 UTC, mremi commented on src/ExtraSessionTrait.php
> +     * Wait the given css element being visible
Previous version was not so bad, isn't it?

2018-12-18 14:28 UTC, mremi commented on src/ExtraSessionTrait.php
> +                return true;
Please add blank line before

2018-12-18 14:28 UTC, mremi commented on src/ExtraSessionTrait.php
> +        }, 'iWaitUntilPageContains::'.$text, $seconds);
`sprintf('%s::%s', __METHOD__, $text)`

2018-12-18 14:28 UTC, mremi commented on src/ExtraSessionTrait.php
> +    public function iClickOnCssElement($selector)
Still relevant, please remove this method

2018-12-18 14:28 UTC, mremi commented on src/ExtraSessionTrait.php
> +        throw new ExpectationException(sprintf('Spin function timed out after %d seconds: %s', $wait, $message), $this->getSession());
please add blank line before

2018-12-18 14:28 UTC, mremi commented on src/ExtraSessionTrait.php
> +    protected function spin($callback, $message, $wait = 60)
please add type hinting `callable`

2018-12-18 14:28 UTC, mremi commented on src/ExtraWebAssertTrait.php
> +    public function assertElementNotVisible($selector)
Equivalent of `iWaitForCssElementBeingInvisible`?

2018-12-18 14:28 UTC, mremi commented on src/ExtraWebAssertTrait.php
> +use PHPUnit\Framework\Assert;
So we should add `phpunit/phpunit` in composer.json in `require` section, maybe it would be better to only throw an exception instead of using phpunit

2018-12-18 14:28 UTC, mremi commented on src/ExtraWebAssertTrait.php
> +        $message = sprintf( '%d "%s" found on the page, but should at least %d.', \count($elements), $selector, $num);
please remove extra whitespace

2018-12-18 14:28 UTC, mremi commented on src/ExtraWebAssertTrait.php
> +    public function assertElementVisible($selector)
Equivalent of `iWaitForCssElementBeingVisible`?

2019-01-16 12:39 UTC, mremi commented on src/ExtraSessionTrait.php
> -
please re-add it

2019-01-16 12:39 UTC, mremi commented on src/ExtraSessionTrait.php
> +     * Wait the given css element being masked
please re-add `for`

2019-01-16 12:39 UTC, mremi commented on src/ExtraSessionTrait.php
> -
please re-add it

2019-01-16 12:39 UTC, mremi commented on src/ExtraWebAssertTrait.php
> -
please re-add it

2019-01-16 12:39 UTC, mremi commented on src/ExtraWebAssertTrait.php
> -
please re-add it

2019-01-16 12:39 UTC, mremi commented on tests/ExtraSessionTraitTest.php
> -
please re-add it

2019-01-16 12:39 UTC, mremi commented on tests/ExtraSessionTraitTest.php
> -
please re-add it

2019-01-16 12:39 UTC, mremi commented on tests/ExtraSessionTraitTest.php
> -
please re-add it

2019-01-16 12:39 UTC, mremi commented on tests/ExtraSessionTraitTest.php
> -
please re-add it

2019-01-16 12:39 UTC, mremi commented on tests/ExtraWebAssertTraitTest.php
> -
please re-add it

2019-01-16 12:39 UTC, mremi commented on tests/ExtraWebAssertTraitTest.php
> -
please re-add it

2019-01-16 12:39 UTC, mremi commented on tests/ExtraWebAssertTraitTest.php
> -
please re-add it

2019-01-16 12:39 UTC, mremi commented on tests/ExtraWebAssertTraitTest.php
> -
please re-add it

2019-02-06 14:24 UTC, mremi commented
@bdejacobet any news?

2019-02-15 08:12 UTC, mremi commented
@bdejacobet Could you please rebase?

2019-02-15 11:09 UTC, mazsudo requested changes

2019-02-15 11:09 UTC, bmaziere commented on tests/ExtraSessionTraitTest.php
> +    public function testIWaitPageContains()
add `: void` return types everywhere plz

2019-02-15 11:09 UTC, bmaziere commented on tests/ExtraSessionTraitTest.php
> +     * @return \PHPUnit_Framework_MockObject_MockObject
use MockObject plz ;) (and also in return type)

2019-02-15 11:09 UTC, bmaziere commented on src/ExtraSessionTrait.php
> +    protected function spin(callable $callback, $message, $wait = 60)
seems useless now as wait do the job ;)

2019-02-19 09:26 UTC, mazsudo approved these changes

2019-02-19 09:27 UTC, bmaziere commented
ok for you @mremi ?

2019-02-19 09:47 UTC, merged